### ISSUE TITLE
Difference between json saved and json published

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#111]
We made a different json structure when:

- we use structured data to represent rich labels when saving a questionnaire 
- we use a regular string when publishing these structured data.

Are there many other differences between json saved and json published?

**Comment by BoogalooJB** [comment]
The differences are the result of the  `serializeQuestionnaire` `function` in https://github.com/InseeFr/Pogues/blob/abaf87574d3f88933f4f14e577a5e1dafe563339/src/js/utils/data-json-utils.js. I think there is no other difference since the published questionnaire is produced with (https://github.com/InseeFr/Pogues/blob/abaf87574d3f88933f4f14e577a5e1dafe563339/src/js/actions/questionnaire.js#L179-L186) :
```javascript
//publish questionnaire action
const qr = questionnaireToModel(getState(), id)
return stromaePostQuestionnaire(serializeQuestionnaire(qr))...
```
Some work on the case:
https://github.com/InseeFr/Pogues/blob/abaf87574d3f88933f4f14e577a5e1dafe563339/src/js/utils/data-json-utils.js#L9-L12

Some fields are renamed: https://github.com/InseeFr/Pogues/blob/abaf87574d3f88933f4f14e577a5e1dafe563339/src/js/utils/data-json-utils.js#L14-L32
