### ISSUE TITLE
Edit a code list (ergonomics)

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#118]
We want to keep the new ergonomic of the code list editor but:
- we lost the up and down arrows to order categories;
- we want to enlarge the input fields to enter categories (for example in enlarging the code list editor in the whole page)

**Comment by BoogalooJB** [comment]
Arrows had never been working, that's why they have been removed. I can make them work if needed.
About wider input fields, it can be fixed but it's not trivial (for now it's attached to the code list selector, and since the selector takes half the screen, it cannot use more space). Does it have priority ?

**Comment by ThomasPO** [comment]
Fixed
