### ISSUE TITLE
Ensure only numbers can be typed in number fields

### ISSUE THREAD

**Issue by jbrudant** [InseeFr/Pogues#123]
In recent versions of Chrome, it seems to be default behaviour for fields declared with a "number" `type`, but we need to catch attempts to put something else than a number for other browsers. See comments in #112

**Comment by BoogalooJB** [comment]
I'm confused. I don't understand why firefox let us type in something else than a number. If we try to catch this in the reducer, it's not trivial:
- for chrome, the actual value returned when invalid character was typed in seems to be the previous value : we can check if this value is ok (empty string is ok too), and if not, ignore it ;
- for firefox, it seems to be an empty string, so we cannot differentiate when an empty string was filled in (correct behaviour), and was the empty string replaces an invalid input.

I must be wrong somewhere, I'm running out of time for now. Can we stay with the current behaviour (working in chrome) ? Invalid information will be serialized with `null` (which is expected behaviour for numeric fields which have not been filled in).

**Comment by BoogalooJB** [comment]
Even trying to implement a degraded behaviour in Firefox (replace an invalid input by an empty string, and not the value before the invalid character was typed in) is not easy: we encounter this problem : https://github.com/facebook/react/issues/3810. The component does not seem to update itself.

In a previous version of Pogues, we used `parseInt` in the event handler and it seemed to work.
