### ISSUE TITLE
Problem with 'Component' component

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Pogues#14]
For the rendering of the questionnaire, we have React components 'Component', 'Sequence' and 'Question' mapping the corresponding model classes. Component is a superclass of Sequence and Question.

When structuring the rendering as Sequence -> Component -> Sequence or Question (see commit 333b1e8de41f3de789a4a2e002bdcd2f106bf9d4), the rendering bugs when there are sequences of depth 2 (ie sequences that are nested in others).

We have messages like: 'Warning: Only functions of strings can be mounted as React components', often followed by 'TypeError: element.type is not a constructor', and the questionnaire is not rendered at all.

Changing the rendering structure to Sequence -> Sequence or Question (see commit cd38356620c5cb513eb5fc6be649b3dc74e30d68) seems to solve the problem.

**Comment by FranckCo** [comment]
Reassigning to RT who will file a issue on React's repo.

**Comment by BoogalooJB** [comment]
The message is due to Component or Sequence being an object, not a function. The problem comes from circular dependencies, not allowed with require.

**Comment by BoogalooJB** [comment]
Maybe I misunderstood what the problem was, but I think I fixed it (sorry if I'm wrong).

**Comment by romaintailhurat** [comment]
No, as i say this noon, that was the problem (the react component being an object and not a function). Sorry, I wasn't aware of the circular dependency problem, good job for pointing to that JB, your changes seems to do the trick.

Maybe we could have a cleaner approach if we could inject the dependency, but because we're working with React component, i'm not sure how this could be done, maybe with Mixins ?

**Comment by FranckCo** [comment]
Resolved
