### ISSUE TITLE
A problem with the Pogues2DDI transformation?

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#778]
Strange case this [questionnaire](https://conception-questionnaires.demo.insee.io/questionnaire/lswzvvrw). 🤔 

A 1st visualisation is in error:

```
Eno generation error: An error was occured during the xml-pogues2ddi transformation. 
An empty sequence is not allowed as the first argument of enopogues:is-not-collected().
Found while atomizing the result of a call to enopogues:is-not-collected#1 in {xsl:apply-templates} on line 1142. 
Found while atomizing the result of a call to enopogues:is-not-collected#1 in {xsl:apply-templates} on line 1142 : Error in :/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi.xsl ; SystemID: ; Line#: 2247; Column#: 66
```

(a problem with the "not collected" devs in the Pogues2DDI transformation?)

If the questions variables are regenerated, the errors disappear.

But, after saving and getting back to the questionnaires, the same error appears again.

**Comment by QRuhier** [comment]
Problem due to "other, specify" variables in single-choice and multiple-choice questions. After reloading questionnaire, there were lost since v1.5.13

Changes :
- fix single-choice and multiple-choice questions having "specify"
- remove the buttons "add specify" and "edit specify" in table (currently we can add one but since 1.5.7 the variable is not generated so it is useless)

**Comment by AnneHuSKa** [comment]
ok, testé et validé avec version [1.5.14-rc.1](https://github.com/InseeFr/Pogues/releases/tag/1.5.14-rc.1)
